version: '3.8'

services:
  shard-A:
    image: postgres:15-alpine
    container_name: infra_shard-A_1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard-A
    ports:
      - "5432:5432"

  shard-B:
    image: postgres:15-alpine
    container_name: infra_shard-B_1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard-B
    ports:
      - "5433:5432"

  shard-C:
    image: postgres:15-alpine
    container_name: infra_shard-C_1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard-C
    ports:
      - "5434:5432"

  shard-D:
    image: postgres:15-alpine
    container_name: infra_shard-D_1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard-D
    ports:
      - "5435:5432"

